# 網站設置
title: DEEPSLEEP-V3
SEOTitle: deepsleep-v3的博客 | deepsleep-v3 Blog
header-img: img/home-bg.jpg
email: wontfix@hotmail.com
description: "這裡是 deepsleep-v3 的個人部落格，與你一起發現更大的世界"
keyword: ""
url: "https://deepsleep-v3.github.io" # 你的主機，用於絕對 URL
baseurl: "" # 例如，如果你的博客託管在 'host/blog'，則設為 '/blog'

# 發布具有未來日期的文章或集合文檔。
future: true

# SNS 設置
RSS: false
#zhihu_username: deepsleep-v3
github_username: deepsleep-v3
#twitter_username: deepsleep-v3
#facebook_username: deepsleep-v3

# 構建設置
# 從 2016 年開始，'pygments' 在 GitHub Pages 上已不支持。改用 'rouge' 進行語法高亮。
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # 如果你想自定義錨點。請查看 `post.html` 第 181 行
# 如果在中國有時區問題（例如 #68），取消註釋以使用此設置：
timezone: CN

# Gems
# 來自 PR#40，支持 Jekyll 3.0 的本地預覽
# 確保你已經安裝了這個 gem
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown 設置
# 用 kramdown 替換 redcarpet，
# 雖然 redcarpet 可以自動高亮代碼，但缺乏標題 ID 使得目錄無法實現，所以我切換到 kramdown
# 文檔：http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # 使用 GitHub Flavored Markdown！非常重要
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus 設置
#disqus_username: hux

# 網易雲音樂評論設置
netease_comment: false

# 統計設置
# 百度統計
# ba_track_id: [你的跟蹤 ID]

# 側邊欄設置
sidebar: true # 是否使用側邊欄。
sidebar-about-description: "要做一个锟斤拷的程序猿"
sidebar-avatar: https://github.com/Huxpro.png # 使用絕對 URL，因為它在 `/` 和 `/about/` 中都會使用

# 特色標籤
featured-tags: true # 是否使用特色標籤
featured-condition-size: 0 # 如果標籤的文章數量大於此條件值，該標籤將被展示

# 漸進式 Web 應用
chrome-tab-theme-color: "#AFFFC0"
service-worker: true

# MathJax 渲染用於 layout:page（例如文章預覽）
page-mathjax: true

# 友情鏈接
friends: [
  {
    title: "HMCL++ (Hello Minecraft! Launcher Plus Plus)",
    href: "https://github.com/deepsleep-v3/HMCLPP"
  },
  {
    title: "TT (TypewriTer practice)",
    href: "https://github.com/deepsleep-v3/TT"
  }
]
